/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author M.shefa
 */
public class KelolaKaryawan extends javax.swing.JFrame {
    
    private void tambahCardKaryawan(
            String nama,
            String jabatan,
            String jk,
            String hp,
            String alamat) {

        String id = String.format("K%03d", nomorKaryawan++);

        javax.swing.JPanel card = new javax.swing.JPanel();
        card.setBackground(new java.awt.Color(255, 255, 255));
        card.setBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(46, 135, 246), 2));

        card.setPreferredSize(new java.awt.Dimension(350, 180));

        javax.swing.JLabel lbl = new javax.swing.JLabel(
                "<html>"
                + "<b>ID :</b> " + id + "<br>"
                + "<b>Nama :</b> " + nama + "<br>"
                + "<b>Jabatan :</b> " + jabatan + "<br>"
                + "<b>Jenis Kelamin :</b> " + jk + "<br>"
                + "<b>No HP :</b> " + hp + "<br>"
                + "<b>Alamat :</b> " + alamat + "<br>"
                + "</html>"
        );

        card.add(lbl);
        
        card.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {

                cardTerpilih = card;
                labelTerpilih = lbl;

                card.setBackground(
                        new java.awt.Color(220, 240, 255));
            }
        });

        panelList.add(card);

        panelList.revalidate();
        panelList.repaint();
    }
    
    private void refreshDaftarKaryawan() {

        panelList.removeAll();

        if (daftarKaryawan.isEmpty()) {

            panelList.add(jLabel11);

        } else {

            for (int i = 0; i < daftarKaryawan.size(); i++) {

                String[] data = daftarKaryawan.get(i);

                javax.swing.JPanel card = new javax.swing.JPanel();

                card.setBackground(java.awt.Color.WHITE);

                card.setBorder(
                        javax.swing.BorderFactory.createLineBorder(
                                new java.awt.Color(46, 135, 246), 2));

                javax.swing.JLabel lbl
                        = new javax.swing.JLabel(
                                "<html>"
                                + "<b>ID :</b> " + data[0] + "<br>"
                                + "<b>Nama :</b> " + data[1] + "<br>"
                                + "<b>Jabatan :</b> " + data[2] + "<br>"
                                + "<b>No HP :</b> " + data[4]
                                + "</html>");

                card.add(lbl);

                final int idx = i;

                card.addMouseListener(
                        new java.awt.event.MouseAdapter() {

                    @Override
                    public void mouseClicked(
                            java.awt.event.MouseEvent e) {

                        indexDipilih = idx;

                        jTextField1.setText(data[1]);
                        jTextField2.setText(data[2]);
                        jComboBox1.setSelectedItem(data[3]);
                        jTextField3.setText(data[4]);
                        jTextField4.setText(data[5]);
                    }
                });

                panelList.add(card);
            }
        }

        panelList.revalidate();
        panelList.repaint();
    }
    
    private int nomorKaryawan = 1;
    private boolean dataPertama = true;
    private java.util.ArrayList<String[]> daftarKaryawan
            = new java.util.ArrayList<>();

    private int indexDipilih = -1;
    private int selectedId = -1;
    
    private javax.swing.JPanel cardTerpilih = null;
    private javax.swing.JLabel labelTerpilih = null;
    
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(KelolaKaryawan.class.getName());

    /**
     * Creates new form KelolaKaryawan
     */
    public KelolaKaryawan() {
        initComponents();
        panelList.setLayout(
            new javax.swing.BoxLayout(
                panelList,
                javax.swing.BoxLayout.Y_AXIS
            )
        );

        jComboBox1.addItem("Laki-laki");
        jComboBox1.addItem("Perempuan");

        loadDataKaryawan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnkembali = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        scrollKaryawan = new javax.swing.JScrollPane();
        panelList = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Vladimir Script", 0, 12)); // NOI18N
        jLabel12.setText("Employee Management System");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        btnkembali.setText("KEMBALI");
        btnkembali.addActionListener(this::btnkembaliActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel10.setText("Enterprise");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("HR");

        jLabel13.setFont(new java.awt.Font("Vladimir Script", 0, 12)); // NOI18N
        jLabel13.setText("Employee Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(86, 86, 86))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(46, 135, 246));
        jLabel1.setText("Data Karyawan");

        jLabel2.setText("Nama Karyawan    : ");

        jLabel4.setText("Jabatan                  :");

        jLabel5.setText("Jenis Kelamin        : ");

        jLabel6.setText("No HP                   :");

        jLabel7.setText("Alamat                  :");

        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        btntambah.setBackground(new java.awt.Color(153, 255, 153));
        btntambah.setForeground(new java.awt.Color(51, 51, 51));
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(this::btntambahActionPerformed);

        btnubah.setBackground(new java.awt.Color(153, 204, 255));
        btnubah.setText("UBAH");
        btnubah.addActionListener(this::btnubahActionPerformed);

        btnhapus.setBackground(new java.awt.Color(220, 38, 38));
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(this::btnhapusActionPerformed);

        btnreset.setBackground(new java.awt.Color(209, 213, 219));
        btnreset.setForeground(new java.awt.Color(45, 45, 45));
        btnreset.setText("RESET");
        btnreset.addActionListener(this::btnresetActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21))
                    .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 207, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnubah, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(115, 115, 115))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(46, 135, 246), new java.awt.Color(46, 135, 246), new java.awt.Color(46, 135, 246), new java.awt.Color(46, 135, 246)));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(46, 135, 246));
        jLabel8.setText("Daftar Karyawan");

        jLabel9.setText("Cari Karyawan   :");

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        scrollKaryawan.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollKaryawan.setToolTipText("scrollKaryawan");
        scrollKaryawan.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelList.setLayout(new javax.swing.BoxLayout(panelList, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        panelList.add(jPanel2);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Belum ada data karyawan");
        panelList.add(jLabel11);

        scrollKaryawan.setViewportView(panelList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollKaryawan)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 88, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtcari)
                                .addGap(12, 12, 12)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        String nama = jTextField1.getText();
    String jabatan = jTextField2.getText();
    String jk = jComboBox1.getSelectedItem().toString();
    String hp = jTextField3.getText();
    String alamat = jTextField4.getText();

    model.karyawan k = new model.karyawan();

    k.setNama(nama);
    k.setJabatan(jabatan);
    k.setJenisKelamin(jk);
    k.setNoHp(hp);
    k.setAlamat(alamat);

    dao.karyawanDAO dao = new dao.karyawanDAO();

    if (dao.tambah(k)) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Data berhasil disimpan");
        
        loadDataKaryawan();

        btnresetActionPerformed(null);

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Gagal menyimpan data");
    }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");

        jComboBox1.setSelectedIndex(0);

        indexDipilih = -1;
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
       if (selectedId == -1) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Pilih data dulu!");

        return;
    }

    dao.karyawanDAO dao =
            new dao.karyawanDAO();

    if (dao.hapus(selectedId)) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Data berhasil dihapus");

        loadDataKaryawan();

        selectedId = -1;

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Gagal menghapus data");
    }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
       if (selectedId == -1) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Pilih data dulu!");

        return;
    }

    model.karyawan k;
        k = new model.karyawan();

    k.setId(selectedId);
    k.setNama(jTextField1.getText());
    k.setJabatan(jTextField2.getText());
    k.setJenisKelamin(
            jComboBox1.getSelectedItem().toString());
    k.setNoHp(jTextField3.getText());
    k.setAlamat(jTextField4.getText());

    dao.karyawanDAO dao =
            new dao.karyawanDAO();

    if (dao.update(k)) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Data berhasil diubah");

        loadDataKaryawan();

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Gagal mengubah data");
    }

    }//GEN-LAST:event_btnubahActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
        String keyword = txtcari.getText().trim();

    if (keyword.isEmpty()) {
        loadDataKaryawan();
        return;
    }

    panelList.removeAll();
    jLabel11.setVisible(false);

    try {

        dao.karyawanDAO dao =
                new dao.karyawanDAO();

        java.sql.ResultSet rs =
                dao.cari(keyword);

        while (rs.next()) {

            javax.swing.JPanel card =
                    new javax.swing.JPanel();

            javax.swing.JLabel lbl =
                    new javax.swing.JLabel(
                            "<html>"
                            + "<b>ID :</b> "
                            + rs.getInt("id")
                            + "<br>"
                            + "<b>Nama :</b> "
                            + rs.getString("nama")
                            + "<br>"
                            + "<b>Jabatan :</b> "
                            + rs.getString("jabatan")
                            + "</html>"
                    );

            card.add(lbl);

            panelList.add(card);
        }

        panelList.revalidate();
        panelList.repaint();

    } catch (Exception e) {

        e.printStackTrace();
    }
    }//GEN-LAST:event_txtcariKeyReleased

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
        dispose();

        MainMenuFrame menu = new MainMenuFrame();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelolaKaryawan().setVisible(true));
    }
    private void loadDataKaryawan() {

    panelList.removeAll();
    if(panelList.getComponentCount() == 0){
    panelList.add(jLabel11);
}

    try {

        dao.karyawanDAO dao =
                new dao.karyawanDAO();

        java.sql.ResultSet rs =
                dao.getAll();

        while (rs.next()) {
            
            if (panelList.getComponentCount() == 0) {
    panelList.add(jLabel11);
} else {
    jLabel11.setVisible(false);
}

             final int id = rs.getInt("id");

    final String nama = rs.getString("nama");
    final String jabatan = rs.getString("jabatan");
    final String jk = rs.getString("jenis_kelamin");
    final String hp = rs.getString("no_hp");
    final String alamat = rs.getString("alamat");

    javax.swing.JPanel card = new javax.swing.JPanel();
    card.setPreferredSize(
        new java.awt.Dimension(320,120));

card.setMaximumSize(
        new java.awt.Dimension(
                Integer.MAX_VALUE,120));

card.setBackground(
        java.awt.Color.WHITE);

card.setBorder(
        javax.swing.BorderFactory
                .createLineBorder(
                        new java.awt.Color(
                                46,135,246),2));

    javax.swing.JLabel lbl =
        new javax.swing.JLabel(
                "<html>"
                + "<b>ID :</b> " + id
                + "<br>"
                + "<b>Nama :</b> " + nama
                + "<br>"
                + "<b>Jabatan :</b> " + jabatan
                + "<br>"
                + "<b>Jenis Kelamin :</b> " + jk
                + "<br>"
                + "<b>No HP :</b> " + hp
                + "<br>"
                + "<b>Alamat :</b> " + alamat
                + "<br>"
                + "</html>"
        );

    card.add(lbl);

    card.addMouseListener(
            new java.awt.event.MouseAdapter() {

        @Override
        public void mouseClicked(
                java.awt.event.MouseEvent e) {

            selectedId = id;

            jTextField1.setText(nama);
            jTextField2.setText(jabatan);
            jComboBox1.setSelectedItem(jk);
            jTextField3.setText(hp);
            jTextField4.setText(alamat);
        }
    });

    panelList.add(card);
        }
  panelList.revalidate();
        panelList.repaint();

    } catch (Exception e) {

        e.printStackTrace();
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel panelList;
    private javax.swing.JScrollPane scrollKaryawan;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
